# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -o main ./main.go

    - name: Test
      run: go test -v ./...
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: tx
    steps:
    - name: ssh deploy
    # You may pin to the exact commit or the version.
      uses: easingthemes/ssh-deploy@845b7f6f1fe5c1ae0ebe63114da9d8582ff0de75
      with:
        # Private key part of an SSH key pair
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        # Remote user
        REMOTE_USER: work
        # Remote port
        REMOTE_PORT: 22 # optional, default is 22
        # Source directory, path relative to `$GITHUB_WORKSPACE` root, eg: `dist/`
        SOURCE: /main # optional, default is 
        # Target directory
        TARGET: /home/work/ # optional, default is /home/REMOTE_USER/
        # Arguments to pass to rsync
        ARGS: -rlgoDzvc -i # optional, default is -rlgoDzvc -i
        # An array of ssh arguments, they must be prefixed with -o and separated by a comma, for example: -o SomeArgument=no, -o SomeOtherArgument=5 
        SSH_CMD_ARGS:  -o StrictHostKeyChecking=no # optional, default is -o StrictHostKeyChecking=no
        # paths to exclude separated by `,`, ie: `/dist/, /node_modules/`

   

