# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
    - main
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jerray/work-weixin-notifier@v1.0.0
      with:
        key: ${{ secrets.weixin_key }}
        type: text
        content: '{{ github.Repository }} build finished'
        status: ${{ job.status }}

    - name: send message 
      run: |
        curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=0e19a011-3602-48f4-b20f-0f6b89c2f51a' \
        -H 'Content-Type: application/json' \
        -d '
        {
        "msgtype": "text",
        "text": {
        "content": "send message test"
        }
        }'

